### PR TITLE
Initial work to add FCM to RhoConnect

### PR DESCRIPTION
**Pull request by nhinze**
More testing is needed.

Instructions:
- Add the following gems to the bottom of .rcgemfile in your RhoConnect app:
gem 'google-api-client', '~> 0.31.0'
gem 'google-api-fcm', '~> 0.1.6'

Place credentials JSON file into settings directory. Provide the path to it in env variable GOOGLE_APPLICATION_CREDENTIALS as explained here:

https://firebase.google.com/docs/cloud-messaging/auth-server#provide_credentials_manually

You can use the following env variables for debugging output:
FIREBASE_DEBUG=true
GOOGLE_API_USE_RAILS_LOGGER=false

settings.yml needs two new entries:
  :fcm_project_id: 
  :package_name: com.mybusiness.myapp

### CODE REVIEW

**Comment by nhinze** [comment]
I have completed final testing. I'm able to send a ping from the RhoConnect console and it correctly shows on the device and triggers a sync.

Some additional notes:
- The gems needed are now:

gem 'google-api-client', '~> 0.31.0'
gem 'google-api-fcm', :git => 'https://github.com/oniksfly/google-api-fcm.git'

The push_callback in the app needs to have these changes:

```
    if Rho::System.getProperty('platform') == 'APPLE'
      sources_to_sync = @params['do_sync'] # comma-separated list of data sources we must sync, or "all"
    elsif Rho::System.getProperty('platform') == 'ANDROID'
      sources_to_sync = @params['data']['do_sync'] # comma-separated list of data sources we must sync, or "all"
    end
```

Another note, currently the notification is NOT received if the app is open. If the app is closed or in background, the notification is properly received.

**Comment by vmusulainen** [comment]
I cannot to build rhoconnect gem file with command
`rake install`

The error has been raised
`LoadError: cannot load such file -- google/apis/messages
/Users/mva/projects/nhinze/rhoconnect-fcm/lib/rhoconnect/ping/fcm.rb:1:in require'
/Users/mva/projects/nhinze/rhoconnect-fcm/lib/rhoconnect/ping/fcm.rb:1:in <top (required)>'`

**Comment by nhinze** [comment]
I added the gem dependencies to the rhoconnect.gemspec file.
Run the following commands:
- bundle install
- rake install

**Comment by vmusulainen** [comment]
One question: why you use  rare [google-api-fcm](https://rubygems.org/gems/google-api-fcm) instead widespread gem [fcm](https://rubygems.org/gems/fcm) ?

**Comment by nhinze** [comment]
I use the google-api-fcm gem, because this uses the new API. I'm worried that the fcm gem approach is going to be deprecated soon:

Apps using the FCM legacy HTTP API should consider migrating to the HTTP v1 API. See the migration guide for more information about the v1 API's advantages and for migration instruction.

**Comment by nhinze** [comment]
I have fixed some of the FCM tests. I do not understand how to fix the other tests. I may need your assistance there.

**Pull request merged**
